### PR TITLE
Add filter awset delta mutator

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Brilliant solution.  cc: @tsloughter

**Comment by cmeiklejohn** [comment]
Good to merge, please bump lasp unstable and merge.

**Review by cmeiklejohn — APPROVED** [review]

**Comment by cmeiklejohn** [comment]
Can you bump unstable for this change, @vitorenesduarte?

**Comment by vitorenesduarte** [comment]
@cmeiklejohn https://github.com/lasp-lang/lasp/commit/818cbcd3842a471d6e471eed9beb90dc2942370b

**Pull request merged**
