### PR TITLE
Reduce compute time

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by vitorenesduarte** [comment]
__Before / After__:
```
- delta:
  > min: 12 / 11
  > max: 78437 / 44049
  > avg: 10167 / 5610
- is_bottom:
  > min: 2 / 2
  > max: 35 / 18
  > avg: 2.7 / 3
- is_strict_inflation:
  > min: 11 / 9
  > max: 26203 / 1458
  > avg: 9492 / 494
- merge:
  > min: 9 / 7
  > max: 35771 / 1247
  > avg: 9485 / 488
- mutate:
  > min: 20 / 15
  > max: 17462 / 1467
  > avg: 4118 / 349
- new:
  > min: 3 / 3
  > max: 2700 / 2865
  > avg: 466 / 478
- query:
  > min: 5 / 6
  > max: 905 / 987
  > avg: 179 / 183
```

**Comment by vitorenesduarte** [comment]
Time reduced to:
- __delta__: 55%
- __is_strict_inflation__: 5%
- __merge__: 5%
- __mutate__: 8%

**Comment by vitorenesduarte** [comment]
__Before / After__ (`state_awset`):
```
- delta:
  > min: 12 / 11
  > max: 78437 / 44049
  > avg: 10167 / 3963
- is_bottom:
  > min: 2 / 2
  > max: 35 / 18
  > avg: 2.7 / 3
- is_strict_inflation:
  > min: 11 / 9
  > max: 26203 / 1458
  > avg: 9492 / 189
- merge:
  > min: 9 / 7
  > max: 35771 / 1247
  > avg: 9485 / 179
- mutate:
  > min: 20 / 15
  > max: 17462 / 1467
  > avg: 4118 / 119
- new:
  > min: 3 / 3
  > max: 2700 / 2865
  > avg: 466 / 478
- query:
  > min: 5 / 6
  > max: 905 / 987
  > avg: 179 / 183
```

Time reduced to:
- __delta__: 39%
- __is_strict_inflation__: 2%
- __merge__: 2%
- __mutate__: 3%

**Comment by cmeiklejohn** [comment]
@vitorenesduarte Is this good to merge?

**Comment by vitorenesduarte** [comment]
@cmeiklejohn Yes.

**Pull request merged**
