### PR TITLE
Add missing Causal CRDTs and a LWWRegister

### PR DESCRIPTION
**Pull request by vitorenesduarte**
New Data Types:
- [x] LWWRegister #55 (timestamps are assumed globally unique and consistent with causal order)
- [x] MVRegister #56
- [x] DWFlag #57
- [x] EWFlag #58
- [x] ORMap #59

Others:
- [x] Refactor `state_causal_type.erl` into:
  - [x] DotStore
  - [x] DotSet
  - [x] DotFun
  - [x] DotMap
  - [x] CausalContext
- [x] Change `state_gmap` API (this will break Lasp, PR needed)
- [x] Add new test suite for flag semantics
- [x] Unified API for Registers #61

### CODE REVIEW

**Comment by vitorenesduarte** [comment]
When merging two LWWRegister with the same timestamp, what should happen? Throw an error?
Or can we assume they are unique?

**Comment by cmeiklejohn** [comment]
Can you explain the breaking change in this branch?  We need to have this merged by next week for Erlang User Conference.

**Comment by vitorenesduarte** [comment]
The breaking change is in this [commit](https://github.com/lasp-lang/types/pull/60/commits/af209474a7c7d97728afbe61e591ee37f64f2d6b)
When mutating the state_gmap, the operation is now a triple.

**Comment by vitorenesduarte** [comment]
It's an easy fix on Lasp.

**Comment by cmeiklejohn** [comment]
Can you make a Lasp PR with the associated fix on the partition_fix branch?

**Comment by vitorenesduarte** [comment]
Yes, on it.

**Pull request merged**
