### PR TITLE
Remove delta tag from state-based data types

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Is this change compatible with the Lasp unstable branch?

**Comment by vitorenesduarte** [comment]
Yes.
There's [this PR](https://github.com/lasp-lang/lasp/pull/202).
If this is merged, I'll bump types there again.

**Review by cmeiklejohn — APPROVED** [review]

**Comment by cmeiklejohn** [comment]
Will you make the Lasp PR to bump the dependency?

**Comment by vitorenesduarte** [comment]
https://github.com/lasp-lang/lasp/pull/202 this PR was using this branch `no_delta_tag`.
But I already did a commit to `unstable` to use the master branch again:
[bef2409732d33d84bcfc3ac1c009a7702ee5ed76](https://github.com/lasp-lang/lasp/commit/bef2409732d33d84bcfc3ac1c009a7702ee5ed76)

**Pull request merged**
