### PR TITLE
Simplify data types; implement causal context compression; methods for state-driven and digest-driven

### PR DESCRIPTION
**Pull request by vitorenesduarte**
- [x] remove `dot_set`, `dot_fun` and `dot_map` from data type state
- [x] causal context compression
- [x] add property tests
- [x] remove nested types from composable data types state (e.g., `state_gmap` and `state_pair`)
- [x] implement necessary methods for __state-driven__ and __digest-driven__ synchronization algorithms

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Does this break @junghunyoo's implementation?

**Comment by vitorenesduarte** [comment]
Not sure, but I don't think so. #74 probably did break something, but it should be easy to fix.

**Comment by cmeiklejohn** [comment]
Hrm, this was merged with no review.  Do these changes break compatibility with the Lasp code?

**Comment by cmeiklejohn** [comment]
@gyounes I would appreciate **waiting** for the CI to pass before just merging the code: this is the point of having continuous integration. This is a library that is used by more people than just the LightKone folks.

**Comment by vitorenesduarte** [comment]
I asked @gyounes to review this and CI tests passed.
I had a PR in Lasp that fixes compatibility problem: `Type:delta` API changed.

**Comment by cmeiklejohn** [comment]
I'm just saying that *prior* to the CI passing it was merged according to
GitHub.

**Comment by gyounes** [comment]
@cmeiklejohn You are totally right. That was a bit reckless from my side.

**Pull request merged**
