### PR TITLE
Fix rebar3 dialyzer usage

### PR DESCRIPTION
**Pull request by fishcakez**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Thanks for the PR; do you mind me asking if you're using this library in production or planning to?

**Comment by fishcakez** [comment]
@cmeiklejohn I am just a long time follower and no time user :disappointed:. I was discussing a dialyzer issue with @seancribbs earlier and did the PR because your project is neat :heart: and I happen to maintain the rebar3 dialyzer provider.

**Comment by cmeiklejohn** [comment]
Cool, I wasn't sure if there was another reason.

**Comment by cmeiklejohn** [comment]
Thanks for the PR!

**Pull request merged**
